// apps/admin/app/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { Zap, Loader2 } from 'lucide-react';

interface LoginFormValues {
  email: string;
  password: string;
}

export default function LoginPage() {
  const router = useRouter();
  const [serverError, setServerError] = useState('');

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<LoginFormValues>();

  async function onSubmit(values: LoginFormValues) {
    setServerError('');
    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(values),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        setServerError(data.message ?? 'Invalid email or password');
        return;
      }

      router.push('/');
      router.refresh();
    } catch {
      setServerError('Network error. Please try again.');
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-[var(--color-bg)]">
      <div className="w-full max-w-md">
        {/* Logo */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-[var(--color-primary)] mb-4">
            <Zap className="w-8 h-8 text-[var(--color-accent)]" />
          </div>
          <h1 className="text-2xl font-bold text-[var(--color-primary)]">Njiani Electricals</h1>
          <p className="text-[var(--color-muted)] mt-1">Admin Dashboard</p>
        </div>

        {/* Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-[var(--color-border)] p-8">
          <h2 className="text-xl font-semibold text-[var(--color-primary)] mb-6">Sign in</h2>

          <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1" htmlFor="email">
                Email address
              </label>
              <input
                id="email"
                type="email"
                autoComplete="email"
                {...register('email', { required: 'Email is required' })}
                className="w-full px-4 py-2.5 rounded-lg border border-[var(--color-border)] focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] focus:border-transparent text-sm"
                placeholder="admin@njiani.co.ke"
              />
              {errors.email && (
                <p className="text-red-500 text-xs mt-1">{errors.email.message}</p>
              )}
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1" htmlFor="password">
                Password
              </label>
              <input
                id="password"
                type="password"
                autoComplete="current-password"
                {...register('password', { required: 'Password is required' })}
                className="w-full px-4 py-2.5 rounded-lg border border-[var(--color-border)] focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] focus:border-transparent text-sm"
                placeholder="••••••••"
              />
              {errors.password && (
                <p className="text-red-500 text-xs mt-1">{errors.password.message}</p>
              )}
            </div>

            {serverError && (
              <div className="rounded-lg bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-700">
                {serverError}
              </div>
            )}

            <button
              type="submit"
              disabled={isSubmitting}
              className="w-full flex items-center justify-center gap-2 bg-[var(--color-accent)] hover:bg-red-600 text-white font-medium py-2.5 px-4 rounded-lg transition-colors disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {isSubmitting && <Loader2 className="w-4 h-4 animate-spin" />}
              {isSubmitting ? 'Signing in…' : 'Sign in'}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}

// apps/admin/src/routes/login/+page.svelte
<script lang="ts">
	import { api } from '$lib/api/client';
	import { goto } from '$app/navigation';
	import { Loader2, Lock, Mail } from 'lucide-svelte';

	let email = $state('');
	let password = $state('');
	let isSubmitting = $state(false);
	let error = $state('');

	async function handleLogin(e: Event) {
		e.preventDefault();
		isSubmitting = true;
		error = '';

		try {
			await api.auth.login({ email, password });
			goto('/');
		} catch (err: any) {
			error = err.message || 'Login failed. Please check your credentials.';
		} finally {
			isSubmitting = false;
		}
	}
</script>

<div class="min-h-screen bg-gray-50 flex items-center justify-center p-4">
	<div class="max-w-md w-full">
		<div class="text-center mb-10">
			<h1 class="text-3xl font-bold text-gray-900 mb-2 tracking-tight">Njiani Admin</h1>
			<p class="text-gray-500">Sign in to manage your marketplace</p>
		</div>

		<div class="bg-white p-8 rounded-2xl shadow-sm border border-gray-100">
			<form onsubmit={handleLogin} class="space-y-6">
				<div>
					<label for="email" class="block text-xs font-bold uppercase tracking-widest text-gray-400 mb-2">Email Address</label>
					<div class="relative">
						<Mail class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
						<input 
							type="email" 
							id="email" 
							bind:value={email} 
							required
							placeholder="admin@njiani.co.ke"
							class="w-full pl-10 pr-4 py-3 rounded-xl border border-gray-200 focus:border-primary outline-none transition-all" 
						/>
					</div>
				</div>

				<div>
					<label for="password" class="block text-xs font-bold uppercase tracking-widest text-gray-400 mb-2">Password</label>
					<div class="relative">
						<Lock class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
						<input 
							type="password" 
							id="password" 
							bind:value={password} 
							required
							placeholder="••••••••"
							class="w-full pl-10 pr-4 py-3 rounded-xl border border-gray-200 focus:border-primary outline-none transition-all" 
						/>
					</div>
				</div>

				{#if error}
					<div class="bg-red-50 text-red-500 p-4 rounded-xl text-sm font-medium">
						{error}
					</div>
				{/if}

				<button 
					type="submit"
					disabled={isSubmitting}
					class="w-full bg-primary hover:bg-primary/90 text-white py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg shadow-primary/10 disabled:opacity-50"
				>
					{#if isSubmitting}
						<Loader2 class="animate-spin" size={20} />
					{/if}
					Sign In
				</button>
			</form>
		</div>
		
		<p class="text-center mt-8 text-sm text-gray-400">
			&copy; 2024 Njiani Electricals Limited
		</p>
	</div>
</div>
